// Generated by https://quicktype.io

export interface NewResponse {
    status:       string;
    totalResults: number;
    results:      Result[];
    nextPage:     string;
}

export interface Result {
    article_id:      null | string;
    title:           string;
    link:            string;
    keywords:        string[] | null;
    creator:         string[] | null;
    video_url:       null;
    description:     null | string;
    content:         Content ;
    pubDate:         Date;
    image_url:       null | string;
    source_id:       string;
    source_url:      null | string;
    source_icon:     null | string;
    source_priority: number;
    country:         string[];
    category:        string[];
    language:        Language;
    ai_tag:          AITag;
    sentiment:       AITag;
    sentiment_stats: AITag;
    ai_region:       AIRegion;
}

export enum AIRegion {
    OnlyAvailableInCorporatePlans = "ONLY AVAILABLE IN CORPORATE PLANS",
}

export enum AITag {
    OnlyAvailableInProfessionalAndCorporatePlans = "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
}

export enum Content {
    OnlyAvailableInPaidPlans = "ONLY AVAILABLE IN PAID PLANS",
}

export enum Language {
    English = "english",
}

export interface ResultsByCategoryAndPage {
    [key: string] : {
        page: number ,
        results: Result[]
    }
}